### PR TITLE
Fix block and single-line SASS comments

### PR DESCRIPTION
**Pull request by mcmillion**
#9 Fixes block and single-line SASS comments to behave correctly.

### CODE REVIEW

**Comment by pzi** [comment]
Not sure if this is relevant to what @mcmillion has raised, but when a glob is used, the following couple of lines fall over with the highlighting...

screen shot 2015-05-21 at 12 42 34

**Comment by lunelson** [comment]
@P233 I don't use Sass syntax actually, but now that I try the example above I see the same thing

**Comment by naoyeye** [comment]
screen shot 2015-05-26 at 4 44 17 pm

+1

**Comment by naoyeye** [comment]
https://github.com/P233/Syntax-highlighting-for-Sass/tree/3.0

I found this branch has solved the issue.

screen shot 2015-08-22 at 11 17 08 am

**Comment by agauniyal** [comment]
Is there any status for this PR?

**Pull request closed without merging**
